if [ -n "${BASH_VERSION:-}" ]; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  fi

  set -o vi

  net_header() {
    printf '\n== %s ==\n' "$1"
  }

  check-self() {
    net_header "hostname"
    hostname
    net_header "interfaces"
    ip -brief addr
    net_header "routes"
    ip route
    net_header "listeners"
    ss -lntp
    net_header "dns"
    cat /etc/resolv.conf
    net_header "forward rules"
    iptables -vnL FORWARD
  }

  check-router() {
    check-self
  }

  check-brain() {
    net_header "resolve brain"
    nslookup brain 127.0.0.1
    net_header "route to brain"
    ip route get 172.20.0.11
    net_header "tcp probe to brain:9000"
    printf 'hello\n' | nc -w 2 brain 9000
  }

  sniff-brain() {
    tcpdump -ni eth1 host brain
  }

  sniff-9000() {
    tcpdump -ni any tcp port 9000
  }

  l2-neighbors() {
    local iface="${1:-eth0}"
    net_header "arp neighbors on ${iface}"
    ip neigh show dev "${iface}"
    net_header "active arp scan on ${iface}"
    arp-scan --interface="${iface}" --localnet
  }

  demo-reset() {
    net_header "demo reset"
    printf 'Zeroing FORWARD counters on router.\n'
    iptables -Z FORWARD
    net_header "forward counters"
    iptables -vnL FORWARD
  }

  export PS1='[\u@\h \W]\$ '
  alias ll='ls -alF'
  alias la='ls -A'
  alias l='ls -CF'
  alias ifaces='ip -brief addr'
  alias routes='ip route'
  alias ports='ss -lntp'
  alias fw='iptables -vnL'
  alias dns='cat /etc/resolv.conf'
fi
