port=53
no-resolv
bind-interfaces
listen-address=127.0.0.1,172.21.0.254,172.20.0.254
local-ttl=1

address=/left_arm/172.21.0.11
address=/right_arm/172.21.0.12
address=/brain/172.20.0.11
local=/left_arm/
local=/right_arm/
local=/brain/

address=/left-arm/172.21.0.11
address=/right-arm/172.21.0.12
local=/left-arm/
local=/right-arm/
